// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGEYrL2EnxK6jOGsqXj4edU7hazWIKFo',
    appId: '1:291413121362:web:1e7c79d6b68ee9b36a428b',
    messagingSenderId: '291413121362',
    projectId: 'alharamin-app',
    authDomain: 'alharamin-app.firebaseapp.com',
    storageBucket: 'alharamin-app.firebasestorage.app',
    measurementId: 'G-VDQC736K7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv80oYGxTXfegK0odLHmw5NaI7QMEqt10',
    appId: '1:291413121362:android:cbe2902f88fa77326a428b',
    messagingSenderId: '291413121362',
    projectId: 'alharamin-app',
    storageBucket: 'alharamin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCedQnRYTZOO2Q5YXFT3yFT-haPmUtu7aA',
    appId: '1:291413121362:ios:4154b98c2d0f02786a428b',
    messagingSenderId: '291413121362',
    projectId: 'alharamin-app',
    storageBucket: 'alharamin-app.firebasestorage.app',
    iosBundleId: 'com.example.alharaminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCedQnRYTZOO2Q5YXFT3yFT-haPmUtu7aA',
    appId: '1:291413121362:ios:4154b98c2d0f02786a428b',
    messagingSenderId: '291413121362',
    projectId: 'alharamin-app',
    storageBucket: 'alharamin-app.firebasestorage.app',
    iosBundleId: 'com.example.alharaminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMGEYrL2EnxK6jOGsqXj4edU7hazWIKFo',
    appId: '1:291413121362:web:58cf8750635e2c826a428b',
    messagingSenderId: '291413121362',
    projectId: 'alharamin-app',
    authDomain: 'alharamin-app.firebaseapp.com',
    storageBucket: 'alharamin-app.firebasestorage.app',
    measurementId: 'G-32V6BQB729',
  );
}
